import Head from 'next/head'
import IndexCarousel from '../components/IndexCarousel'
import IndexGrid from '../components/IndexGrid'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <IndexCarousel />
      <IndexGrid />
    </>
  )
}
export default Home
